name: Java Selenium Test Automation

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR creation to the main branch

jobs:
  build:
    runs-on: ubuntu-22.04  # Choose the OS environment for the runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java JDK (example with OpenJDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Set the version of Java you are using
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          cd "JavaSelenium P1/ecart"  # Navigate to the directory where pom.xml is located
          mvn install

      # Step 4: Run the Selenium tests
      - name: Run Selenium tests
        run: |
          cd "JavaSelenium P1/ecart"  # Navigate to the directory where pom.xml is located
          mvn test

      # Step 5: Install dependencies (using Maven)
      - name: Install dependencies
        run: mvn install

      # Step 6: Run the Selenium tests
      - name: Run Selenium tests
        run: mvn test

      # Step 7: Optional - Save test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-classes  # Specify the directory where your test results are stored
