name: Java Selenium Test Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Explicitly use Ubuntu 22.04 for now

    steps:

  # Step 3: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify pom.xml exists
        run: ls "JavaSelenium_P1/ecart"
  
      # Step 1: Set up JDK 17 (for Java 17 projects)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
        
      # Step 2: Check Java version to ensure JDK 17 is used
      - name: Check Java version
        run: java -version

     # Step 4: Set up Maven (optional if Maven version is specified)
     # - name: Set up Maven
     #  uses: actions/setup-java@v2
     #  with:
     #    java-version: '17'
     #    maven-version: '3.8.1'

      
  

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          cd "JavaSelenium_P1/ecart"  # Navigate to the directory with pom.xml
          mvn clean install -U
         
          
     # Step 6: Run tests
      #- name: Run tests
      #  run: |
     #     cd "JavaSelenium_P1/ecart"  # Navigate to the directory with pom.xml
      #    mvn test  # Run tests

      - name: Run TestNG tests using testng.xml
        run: |
          cd "JavaSelenium_P1/ecart"  # Navigate to the directory containing testng.xml
          mvn test -DsuiteXmlFiles=testng.xml  # Run TestNG using the testng.xml file
        continue-on-error: true

      - name: Upload Extent Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: JavaSelenium_P1/ecart/reports/extentReports/index.html  # Path to the generated Extent Report HTML file
